### PR TITLE
Update switch_example.ino

### PR DESCRIPTION
**Pull request by Vinay917**
VNY TV

### CODE REVIEW

**Comment by Vinay917** [comment]
12/08/2018 Vinay Annagauni
Please approve this change this is for sinric smart skill to turn on/off the fire tv using alexa voice commads

**Comment by Vinay917** [comment]
# @kakopappa can you merge this pull request to master sinric so that I can use smart skill on my alexa

**Comment by kakopappa** [comment]
@Vinay917 I cannot merge this. This has your wifi and api key. Do not upload your API key to github or any other public server

**Comment by Vinay917** [comment]
Hi Aruna, thanks for your review.

So this is my first time and to make this skill work where should I place
the file si that alexa picks the code.?

Vinay

**Pull request closed without merging**
